name: conda-store-server-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python ==3.10
  # conda builds
  - conda ==23.5.2
  # dev dependencies
  - aiohttp>=3.8.1
  - pytest
  - pytest-celery
  - pytest-mock
  - docker-py<7  # for docker-compose
  - docker-compose
  # build dependencies
  - hatch
  - build
  - pip
  - pip:
      - pytest-playwright
      - twine>=5.0.0
      - pkginfo>=1.10
