name: conda-store-server
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python ==3.10
  # conda environment builds
  - conda ==23.5.2
  - python-docker
  - conda-docker >= 0.1.2
  - conda-pack
  - conda-lock >=1.0.5
  - conda-package-handling
  - conda-package-streaming
  # web server
  - celery
  - flower # not used by server but helpful to debug
  - redis-py
  - sqlalchemy<=1.4.47
  - alembic
  - psycopg2
  - pymysql
  - requests
  - pyyaml #TODO: @trallard check, not in use per https://github.com/conda-incubator/conda-store/pull/19/files
  - uvicorn
  - fastapi
  - pydantic < 2.0
  - traitlets
  - yarl
  - pyjwt
  - filelock
  - itsdangerous
  - jinja2
  - python-multipart
  # artifact storage
  - minio
  # installer
  - constructor
