[build-system]
requires = ["hatchling>=1.14.0", "hatch-vcs", "hatch-fancy-pypi-readme"]
build-backend = "hatchling.build"

[project]
name = "conda-store-server"
description = "Conda Environment Management, Builds, and Serve"
license = "BSD-3-Clause"
requires-python = ">=3.8"
keywords = ["conda"]
authors = [
  { name = "Christopher Ostrouchov", email = "chris.ostrouchov@gmail.com" },
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Build Tools",
  "License :: OSI Approved :: BSD License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
  "conda-docker; sys_platform == 'linux'",
  "conda-pack",
  "celery",
  "sqlalchemy",
  "requests",
  "fastapi",
  "pyyaml",
  "redis",
  "pydantic<2",
  "minio",
  "traitlets",
  "pyjwt",
  "yarl",
  "filelock",
  "itsdangerous",
  "jinja2",
  "python-multipart",
  "python-docker"
  # conda (which should not be included here)
]
dynamic = ["version", "readme"]

[project.urls]
Homepage = "https://conda.store/"
Source = "https://github.com/conda-incubator/conda-store/conda-store-server"

[tool.hatch.version]
source = "vcs"
# need to specify root as .git is one level up
raw-options = {root="../", relative_to="pyproject.toml", local_scheme="node-and-date"}

[tool.hatch.metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"

[[tool.hatch.metadata.hooks.fancy-pypi-readme.fragments]]
text = """<p align="center">
  <a href="https://conda.store/">
    <img src="https://github.com/conda-incubator/conda-store/blob/main/docusaurus-docs/static/img/logo.svg" width="35%" alt="conda-store logo - conda.store homepage" />
  </a>
</p>

"""

[[tool.hatch.metadata.hooks.fancy-pypi-readme.fragments]]
path = "README.md"

[[tool.hatch.metadata.hooks.fancy-pypi-readme.fragments]]
text = "## About the conda-store ecosystem"

[[tool.hatch.metadata.hooks.fancy-pypi-readme.fragments]]
path = "../README.md"
start-after = "<!-- teaser-begin -->"

[project.optional-dependencies]
dev = ["build", "twine"]

[tool.hatch.envs.dev]
dependencies = [
  "pre-commit",
  "pytest",
  "pytest-mock",
  "pytest-playwright",
]

[tool.hatch.envs.dev.scripts]
lint = ["pre-commit run --all"]
unit-test = "pytest tests -v"
playwright-test = [
  "playwright install",
  "pytest --video on ../tests/test_playwright.py"
]
integration-test = ["pytest ../tests/test_api.py ../tests/test_metrics.py"]

[tool.hatch.build.hooks.custom]

[tool.hatch.build.targets.sdist.hooks.custom]

[project.scripts]
conda-store-server = "conda_store_server.server.__main__:main"
conda-store-worker = "conda_store_server.worker.__main__:main"

[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311']


# TODO: add more ruff rules
[tool.ruff]
ignore = [
  "E501", # line-length

]

[tool.check-wheel-contents]
# ignore alembic migrations https://github.com/jwodder/check-wheel-contents?tab=readme-ov-file#w004--module-is-not-located-at-importable-path
ignore = ["W004"]
