# environment used in Docker images and docker-compose
name: conda-store
channels:
  - conda-forge
dependencies:
  - jupyterhub<2.0.0
  - jupyterlab>4.0
  - nb_conda_kernels
  - nodejs=18
  - yarn
  # installer
  - constructor # runtime dep but must be conda installed
  - pip
  - pip:
      - jupyter-launcher-shortcuts
      - jupyterlab-conda-store
