name: conda-store
channels:
  - conda-forge
dependencies:
  - jupyterhub<2.0.0
  - jupyterlab>4.0
  - nb_conda_kernels
  - nodejs=18
  - yarn
  - pip
  - pip:
      - https://github.com/yuvipanda/jupyter-launcher-shortcuts/archive/refs/heads/master.zip
      - jupyterlab-conda-store
