name: conda-store
channels:
  - conda-forge
dependencies:
  - pip
  - jupyterhub<2.0.0
  - jupyterlab>=3.0.0
  - nb_conda_kernels
  - nodejs>=18.0
  - yarn
  # conda-store client dependencies
  - yarl
  - aiohttp>=3.8.1
  - rich
  - click
  - ruamel.yaml
  - pip:
      - https://github.com/yuvipanda/jupyter-launcher-shortcuts/archive/refs/heads/master.zip
      - jupyterlab-conda-store
