[build-system]
requires = ["hatchling>=1.14.0", "hatch-vcs", "hatch-fancy-pypi-readme"]
build-backend = "hatchling.build"

[project]
name = "conda-store"
description = "conda-store client"
license = "BSD-3-Clause"
requires-python = ">=3.8"
keywords = ["conda"]
authors = [
  { name = "Christopher Ostrouchov", email = "chris.ostrouchov@gmail.com" },
]
maintainers = [{ name = "Tania Allard", email = "trallard@bitsandchips.me" }]
# TODO: update maintainers
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Build Tools",
  "License :: OSI Approved :: BSD License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3 :: Only",
  "Intended Audience :: Developers",
  "Intended Audience :: Information Technology",
  "Intended Audience :: Science/Research",
  "Intended Audience :: System Administrators",
]
dependencies = ["rich", "click", "yarl", "aiohttp", "ruamel.yaml"]
dynamic = ["version", "readme"]

[project.urls]
Homepage = "https://conda.store/"
Source = "https://github.com/conda-incubator/conda-store/conda-store"

[tool.hatch.version]
source = "vcs"
# need to specify root as .git is one level up
raw-options = {root="../", relative_to="pyproject.toml", local_scheme="node-and-date"}

[tool.hatch.metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"

[[tool.hatch.metadata.hooks.fancy-pypi-readme.fragments]]
text = """<p align="center">
  <a href="https://conda.store/">
    <img src="https://github.com/conda-incubator/conda-store/blob/main/docusaurus-docs/static/img/logo.svg" width="35%" alt="conda-store logo - conda.store homepage" />
  </a>
</p>

"""

[[tool.hatch.metadata.hooks.fancy-pypi-readme.fragments]]
path = "README.md"

[[tool.hatch.metadata.hooks.fancy-pypi-readme.fragments]]
text = "## About the conda-store ecosystem"

[[tool.hatch.metadata.hooks.fancy-pypi-readme.fragments]]
path = "../README.md"
start-after = "<!-- teaser-begin -->"

[project.optional-dependencies]
dev = ["build", "twine"]

[tool.hatch.envs.dev]
dependencies = [
  "pre-commit",
  "pytest",
  "pytest-mock",
]

[tool.hatch.envs.dev.scripts]
lint = ["pre-commit run --all"]
test = "pytest tests"

[project.scripts]
conda-store = "conda_store.__main__:main"

[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311']

# TODO: add more ruff rules
[tool.ruff]
ignore = [
  "E501", # line-length

]
